// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConfigItem 表示 .obsidian 下可同步的配置项。
 */
export class ConfigItem {
    "path": string;
    "name": string;
    "version": string;
    "isDir": boolean;
    "description": string;
    "defaultSelected": boolean;
    "isPlugin": boolean;

    /** Creates a new ConfigItem instance. */
    constructor($$source: Partial<ConfigItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("defaultSelected" in $$source)) {
            this["defaultSelected"] = false;
        }
        if (!("isPlugin" in $$source)) {
            this["isPlugin"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigItem($$parsedSource as Partial<ConfigItem>);
    }
}

/**
 * SyncPlan 描述一次同步计划。
 */
export class SyncPlan {
    "mainVaultPath": string;
    "targets": TargetSyncPlan[];

    /** Creates a new SyncPlan instance. */
    constructor($$source: Partial<SyncPlan> = {}) {
        if (!("mainVaultPath" in $$source)) {
            this["mainVaultPath"] = "";
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncPlan {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new SyncPlan($$parsedSource as Partial<SyncPlan>);
    }
}

/**
 * SyncPlanAction 描述同步项将在目标库执行的动作。
 */
export enum SyncPlanAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SyncPlanActionCreate 表示目标库中不存在该配置项。
     */
    SyncPlanActionCreate = "create",

    /**
     * SyncPlanActionOverwrite 表示目标库中已经存在该配置项。
     */
    SyncPlanActionOverwrite = "overwrite",
};

/**
 * SyncPlanItem 描述单个配置项的同步计划。
 */
export class SyncPlanItem {
    "path": string;
    "action": SyncPlanAction;

    /** Creates a new SyncPlanItem instance. */
    constructor($$source: Partial<SyncPlanItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = SyncPlanAction.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncPlanItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncPlanItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncPlanItem($$parsedSource as Partial<SyncPlanItem>);
    }
}

/**
 * SyncRequest 描述一次同步计划请求。
 */
export class SyncRequest {
    "mainVaultPath": string;

    /**
     * 从库
     */
    "targetVaultPaths": string[];

    /**
     * 选择要同步的配置
     */
    "selectedPaths": string[];

    /** Creates a new SyncRequest instance. */
    constructor($$source: Partial<SyncRequest> = {}) {
        if (!("mainVaultPath" in $$source)) {
            this["mainVaultPath"] = "";
        }
        if (!("targetVaultPaths" in $$source)) {
            this["targetVaultPaths"] = [];
        }
        if (!("selectedPaths" in $$source)) {
            this["selectedPaths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncRequest {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targetVaultPaths" in $$parsedSource) {
            $$parsedSource["targetVaultPaths"] = $$createField1_0($$parsedSource["targetVaultPaths"]);
        }
        if ("selectedPaths" in $$parsedSource) {
            $$parsedSource["selectedPaths"] = $$createField2_0($$parsedSource["selectedPaths"]);
        }
        return new SyncRequest($$parsedSource as Partial<SyncRequest>);
    }
}

/**
 * SyncResult 描述一次同步的执行结果。
 */
export class SyncResult {
    "backupPath": string;
    "targets": TargetSyncResult[];

    /** Creates a new SyncResult instance. */
    constructor($$source: Partial<SyncResult> = {}) {
        if (!("backupPath" in $$source)) {
            this["backupPath"] = "";
        }
        if (!("targets" in $$source)) {
            this["targets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResult {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new SyncResult($$parsedSource as Partial<SyncResult>);
    }
}

/**
 * SyncResultItem 描述单个同步项的执行结果。
 */
export class SyncResultItem {
    "path": string;
    "status": SyncResultStatus;
    "error": string;

    /** Creates a new SyncResultItem instance. */
    constructor($$source: Partial<SyncResultItem> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = SyncResultStatus.$zero;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResultItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResultItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncResultItem($$parsedSource as Partial<SyncResultItem>);
    }
}

/**
 * SyncResultStatus 描述单个同步项的最终结果。
 */
export enum SyncResultStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SyncResultStatusCreated 表示新增配置成功。
     */
    SyncResultStatusCreated = "created",

    /**
     * SyncResultStatusOverwrote 表示覆盖配置成功。
     */
    SyncResultStatusOverwrote = "overwrote",

    /**
     * SyncResultStatusFailed 表示同步失败。
     */
    SyncResultStatusFailed = "failed",
};

/**
 * TargetSyncPlan 描述单个目标库的同步计划。
 */
export class TargetSyncPlan {
    /**
     * 当前目标库的绝对路径
     */
    "vaultPath": string;

    /**
     * 按主库选择顺序排列的同步项
     */
    "items": SyncPlanItem[];

    /** Creates a new TargetSyncPlan instance. */
    constructor($$source: Partial<TargetSyncPlan> = {}) {
        if (!("vaultPath" in $$source)) {
            this["vaultPath"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetSyncPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): TargetSyncPlan {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new TargetSyncPlan($$parsedSource as Partial<TargetSyncPlan>);
    }
}

/**
 * TargetSyncResult 描述单个目标库的执行结果。
 */
export class TargetSyncResult {
    "vaultPath": string;
    "items": SyncResultItem[];

    /** Creates a new TargetSyncResult instance. */
    constructor($$source: Partial<TargetSyncResult> = {}) {
        if (!("vaultPath" in $$source)) {
            this["vaultPath"] = "";
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TargetSyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TargetSyncResult {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new TargetSyncResult($$parsedSource as Partial<TargetSyncResult>);
    }
}

/**
 * VaultInfo 表示扫描发现的 Obsidian vault。
 */
export class VaultInfo {
    "path": string;
    "name": string;

    /** Creates a new VaultInfo instance. */
    constructor($$source: Partial<VaultInfo> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultInfo($$parsedSource as Partial<VaultInfo>);
    }
}

// Private type creation functions
const $$createType0 = TargetSyncPlan.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = TargetSyncResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SyncPlanItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = SyncResultItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
