// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * VaultService 向前端暴露 vault 扫描接口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildSyncPlan 根据主库配置和用户选择生成覆盖同步计划，不修改文件。
 */
export function BuildSyncPlan(req: $models.SyncRequest): $CancellablePromise<$models.SyncPlan> {
    return $Call.ByID(3225252696, req).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ExecuteSyncPlan 执行覆盖同步；已有同步任务运行时拒绝新的调用。
 */
export function ExecuteSyncPlan(plan: $models.SyncPlan): $CancellablePromise<$models.SyncResult> {
    return $Call.ByID(2207408831, plan).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLastVaultRoot 返回最近一次加载成功的 Vault 扫描根目录。
 */
export function GetLastVaultRoot(): $CancellablePromise<string> {
    return $Call.ByID(3001162524);
}

/**
 * ListConfigItems 列出 vault 的 .obsidian 下可选择同步的配置项。
 */
export function ListConfigItems(vaultPath: string): $CancellablePromise<$models.ConfigItem[]> {
    return $Call.ByID(3677850622, vaultPath).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenSyncBackupDir 使用系统文件管理器打开完整同步备份目录。
 */
export function OpenSyncBackupDir(backupPath: string): $CancellablePromise<void> {
    return $Call.ByID(63541684, backupPath);
}

/**
 * OpenVaultConfigDir 使用系统文件管理器打开 vault 的 .obsidian 配置目录。
 */
export function OpenVaultConfigDir(vaultPath: string): $CancellablePromise<void> {
    return $Call.ByID(132513533, vaultPath);
}

/**
 * SaveLastVaultRoot 保存最近一次加载成功的 Vault 扫描根目录。
 */
export function SaveLastVaultRoot(root: string): $CancellablePromise<void> {
    return $Call.ByID(3256816299, root);
}

/**
 * ScanVaults 扫描 root 并返回包含 .obsidian/ 的目录。
 */
export function ScanVaults(root: string): $CancellablePromise<$models.VaultInfo[]> {
    return $Call.ByID(4174715004, root).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SyncPlan.createFrom;
const $$createType1 = $models.SyncResult.createFrom;
const $$createType2 = $models.ConfigItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.VaultInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
