// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DevService 向前端暴露开发预设接口。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * RemoveDirectory 删除开发预设生成的测试目录。
 */
export function RemoveDirectory(): $CancellablePromise<void> {
    return $Call.ByID(2779208782);
}

/**
 * ResetTestCases 重建开发预设使用的测试目录。
 */
export function ResetTestCases(): $CancellablePromise<void> {
    return $Call.ByID(2590320143);
}
